# Generated by Django 5.1.1 on 2024-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
